-- SQLite schema for synthetic Cross-Cultural Moral Psychology scaffold.
-- Educational and reproducible research scaffold only.

DROP TABLE IF EXISTS component_map;
DROP TABLE IF EXISTS scenario_notes;
DROP TABLE IF EXISTS risk_factors;

CREATE TABLE component_map (
    component TEXT NOT NULL,
    variable TEXT NOT NULL PRIMARY KEY,
    description TEXT NOT NULL,
    interpretive_warning TEXT NOT NULL
);

CREATE TABLE scenario_notes (
    scenario TEXT PRIMARY KEY,
    description TEXT NOT NULL,
    expected_pattern TEXT NOT NULL
);

CREATE TABLE risk_factors (
    risk_factor TEXT PRIMARY KEY,
    mechanism TEXT NOT NULL,
    possible_dampener TEXT NOT NULL
);

INSERT INTO component_map VALUES
('culture', 'culture', 'Synthetic cultural-context label', 'Do not interpret synthetic contexts as real cultures nations religions or populations'),
('harm', 'harm_sensitivity', 'Synthetic harm-perception or harm-sensitivity dimension', 'Harm may be construed differently across contexts'),
('fairness', 'fairness_sensitivity', 'Synthetic fairness or reciprocity dimension', 'Fairness may mean equality need merit role duty or reciprocity'),
('loyalty', 'loyalty_sensitivity', 'Synthetic loyalty or group-obligation dimension', 'Loyalty can support care or justify partiality'),
('authority', 'authority_sensitivity', 'Synthetic authority or norm-order dimension', 'Authority may be religious legal elder-based customary or institutional'),
('purity', 'purity_sensitivity', 'Synthetic purity sanctity or contamination dimension', 'Purity meaning depends heavily on tradition and context'),
('relationship', 'relational_obligation', 'Synthetic relational-duty and close-other obligation dimension', 'Relational obligation is not the same as corruption or nepotism'),
('learning', 'norm_learning', 'Synthetic norm-learning and socialization dimension', 'Norm learning is culturally structured and developmentally shaped'),
('sanction', 'sanction_expectation', 'Synthetic expected sanction or enforcement strength', 'Sanction expectations vary with meta-norms and institutions'),
('judgment', 'moral_judgment', 'Synthetic culturally weighted moral judgment score', 'Not a real-person or real-culture moral score'),
('enforcement', 'norm_enforcement_tendency', 'Synthetic norm-enforcement tendency', 'Not a real enforcement prediction'),
('pluralism', 'moral_profile_vector', 'Vector of cultural value weights', 'Simplified analytic representation only');

INSERT INTO scenario_notes VALUES
('baseline', 'Average sensitivity values across synthetic contexts', 'Moderate synthetic moral judgment'),
('harm_weighted_context', 'Context places stronger weight on harm and fairness', 'Higher predicted judgment as harm sensitivity rises'),
('relational_context', 'Context places stronger weight on loyalty authority purity and relational obligation', 'Higher judgment under relational and authority dimensions'),
('balanced_context', 'Context uses mixed weighting across moral dimensions', 'Intermediate synthetic moral profile'),
('high_norm_learning', 'High norm learning and sanction expectation', 'Higher norm-enforcement tendency'),
('high_relational_obligation', 'High relational obligation and loyalty', 'Greater partiality or close-other obligation in synthetic scenarios'),
('measurement_caution', 'Same score generated by different moral-weighting profiles', 'Warns against treating cross-cultural scores as directly comparable without validation');

INSERT INTO risk_factors VALUES
('naive_universalism', 'One moral vocabulary is treated as universal', 'Measurement validation local knowledge and construct humility'),
('crude_relativism', 'Variation is mistaken for total incomparability', 'Shared-capacity models and careful pluralist analysis'),
('sampling_bias', 'Narrow populations are mistaken for humanity', 'Diverse samples and non-WEIRD research designs'),
('translation_flattening', 'Key moral terms are treated as equivalent across languages', 'Back-translation local collaborators and linguistic analysis'),
('construct_nonequivalence', 'A measure does not capture the same concept across contexts', 'Measurement invariance tests and qualitative validation'),
('colonial_framing', 'Cultures are ranked through imperial or racial assumptions', 'Power-aware and historically grounded comparison'),
('romantic_relativism', 'All local norms are treated as immune from critique', 'Contextual moral judgment attentive to harm dignity and power'),
('culture_as_container', 'Whole societies are treated as internally uniform', 'Internal diversity dissent minority voices and institutional variation');
